[PHP]
extension_dir = "C:/Jaydeep Dhokai Projects/Library/ecomm-demo-ls/php/ext"
extension = php_openssl.dll
extension = php_curl.dll
extension = php_mbstring.dll
extension = php_pdo_mysql.dll
extension = php_pdo_sqlite.dll
extension = php_sqlite3.dll
; extension = php_xml.dll
extension = php_zip.dll
phar.readonly = Off
output_buffering = 4096
memory_limit = 512M
max_execution_time = 300
